### ISSUE TITLE
tiny CSS suggestion: make label text non selectable

### ISSUE THREAD

**Issue by NahuelGerthVK** [tapioca24/p5.capture#32]
Just a tiny CSS suggestion: make label text non selectable.

```css
.p5c-options label {
  -webkit-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

This way we could prevent unwanted text selection while moving around the recorder UI.

![Image](https://github.com/user-attachments/assets/4341d4cc-c63a-4318-b8ec-3f371fd70c79)
